### ISSUE TITLE
Registry docs publishing failed.

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-zitadel#2]
@vavsab we had to revert the publishing of the Zitadel docs in the Pulumi Registry.

https://github.com/pulumi/registry/pull/2659#issuecomment-1583466680

Reason: the `Repository` property in `provider/resources.go` has the wrong Github organization in the URL:

https://github.com/pulumiverse/pulumi-zitadel/blob/3dc64bc4cef183db669b763c4e696844ab7a821d/provider/resources.go#L80

This value is taken over in a generated file for the Registry, which leads to the docs generation to fail:

https://github.com/pulumi/registry/pull/2657/files#diff-d9508d27dc3156e0bab025ca8746e3a89ef73f2fb051d120953c4f297da6b0fdR10

Can you set update `Repository` value in `provider/resources.go` to `https://github.com/pulumiverse/pulumi-zitadel`?

**Comment by vavsab** [comment]
Sure. Will do it today

**Comment by vavsab** [comment]
@ringods all done! the new version is released
