### ISSUE TITLE
Organization doesn't get deleted

### ISSUE THREAD

**Issue by rafalkrupinski** [pulumiverse/pulumi-zitadel#9]
Hi,

I just deleted organization from my pulumi code; `pulumi up` finished without complains, but the organization is still in the console.

**Comment by vavsab** [comment]
@rafalkrupinski Could you please check again? 
It should be working now in v0.0.13

**Comment by rafalkrupinski** [comment]
Thank you, I will try it.

**Comment by rafalkrupinski** [comment]
looks OK. Thank you!
